apiVersion: apps/v1
kind: Deployment
metadata:
  name: storagemgmtserv
  labels:
    app: storagemgmtserv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storagemgmtserv
  template:
    metadata:
      labels:
        app: storagemgmtserv
    spec:
      containers:
      - name: storagemgmtserv
        image: "{{IMAGE}}"
        ports:
        - containerPort: 3001
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: service-secrets
              key: mongo-uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: service-secrets
              key: jwt-secret
        - name: GCS_BUCKET_NAME
          value: "cc-project-amunim"
        - name: USAGE_MONITORING_SERVICE_URL
          value: "{{USAGE_MNTR_URL}}" # Placeholder
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json # Path to the credentials file
        volumeMounts:
        - name: google-cloud-keys
          mountPath: /var/secrets/google
          readOnly: true
      volumes:
      - name: google-cloud-keys
        secret:
          secretName: gac-keys # Name of the secret containing the Google Cloud credentials
