apiVersion: apps/v1
kind: Deployment
metadata:
  name: storagemgmtserv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storagemgmtserv
  template:
    metadata:
      labels:
        app: storagemgmtserv
    spec:
      containers:
        - name: storagemgmtserv
          image: your-dockerhub-username/storagemgmtserv:latest  # Replace with your Docker image name
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: storagemgmtserv
spec:
  selector:
    app: storagemgmtserv
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
