apiVersion: apps/v1
kind: Deployment
metadata:
  name: storagemgmtserv
  labels:
    app: storagemgmtserv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storagemgmtserv
  template:
    metadata:
      labels:
        app: storagemgmtserv
    spec:
      containers:
      - name: storagemgmtserv
        image: us-central1-docker.pkg.dev/gold-obelisk-445820-s5/us-docker-repo/storagemgmtserv:latest
        ports:
        - containerPort: 3001
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: service-secrets
              key: mongo-uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: service-secrets
              key: jwt-secret
        - name: GCS_BUCKET_NAME
          value: "cc-project-amunim"
        - name: USAGE_MONITORING_SERVICE_URL
          value: "{{USAGE_MNTR_URL}}" # Placeholder
