apiVersion: v1
kind: Service
metadata:
  name: frontendserv
spec:
  selector:
    app: frontendserv
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # Use NodePort for local testing or LoadBalancer for cloud environments
