name: Deploy Microservices to Kubernetes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: gold-obelisk-445820-s5
      REGION: us-central1
      REPO_HOST: us-central1-docker.pkg.dev
      REPO_NAME: us-docker-repo

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Authenticate Docker with Artifact Registry
        run: |
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://${{ env.REPO_HOST }}

      - name: Build and Push Docker Images
        run: |
          docker build -t ${{ env.REPO_HOST }}/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/usagemntrserv:latest ./UsageMntrServ
          docker push ${{ env.REPO_HOST }}/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/usagemntrserv:latest

          docker build -t ${{ env.REPO_HOST }}/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/useraccmgmtserv:latest ./UserAccMgmtServ
          docker push ${{ env.REPO_HOST }}/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/useraccmgmtserv:latest

          docker build -t ${{ env.REPO_HOST }}/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/storagemgmtserv:latest ./StorageMgmtServ
          docker push ${{ env.REPO_HOST }}/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/storagemgmtserv:latest

  deploy_to_kubernetes:
    runs-on: ubuntu-latest
    needs: build_and_push

    env:
      PROJECT_ID: gold-obelisk-445820-s5
      REGION: us-central1
      REPO_HOST: us-central1-docker.pkg.dev
      REPO_NAME: us-docker-repo
      KUBECONFIG_PATH: /tmp/kubeconfig

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Install GKE Auth Plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin
          export USE_GKE_GCLOUD_AUTH_PLUGIN=True

      - name: Configure Kubernetes Access
        run: |
          gcloud container clusters get-credentials microservices-cluster --region ${{ env.REGION }} --project ${{ env.PROJECT_ID }}

      - name: Deploy Secrets to Kubernetes
        run: |
          kubectl create secret generic service-secrets \
            --from-literal=mongo-uri=${{ secrets.MONGO_URI }} \
            --from-literal=jwt-secret=${{ secrets.JWT_SECRET }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy and Restart All Services
        run: |
          # Deploy UsageMntrServ
          sed "s|{{IMAGE}}|${{ env.REPO_HOST }}/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/usagemntrserv:latest|g" UsageMntrServ/usagemntrserv-deployment.yaml | kubectl apply -f -
          kubectl apply -f UsageMntrServ/usagemntrserv-service.yaml
          kubectl rollout restart deployment/usagemntrserv

          # Deploy UserAccMgmtServ
          sed "s|{{IMAGE}}|${{ env.REPO_HOST }}/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/useraccmgmtserv:latest|g" UserAccMgmtServ/useraccmgmtserv-deployment.yaml | kubectl apply -f -
          kubectl apply -f UserAccMgmtServ/useraccmgmtserv-service.yaml
          kubectl rollout restart deployment/useraccmgmtserv

          # Deploy StorageMgmtServ
          sed "s|{{IMAGE}}|${{ env.REPO_HOST }}/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/storagemgmtserv:latest|g" StorageMgmtServ/storagemgmtserv-deployment.yaml | kubectl apply -f -
          kubectl apply -f StorageMgmtServ/storagemgmtserv-service.yaml
          kubectl rollout restart deployment/storagemgmtserv

      - name: Deploy Ingress
        run: |
          kubectl apply -f k8s/ingress.yaml

  log_and_update:
    runs-on: ubuntu-latest
    needs: deploy_to_kubernetes

    env:
      PROJECT_ID: gold-obelisk-445820-s5
      REGION: us-central1

    steps:
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Install GKE Auth Plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin
          export USE_GKE_GCLOUD_AUTH_PLUGIN=True

      - name: Configure Kubernetes Access
        run: |
          gcloud container clusters get-credentials microservices-cluster --region ${{ env.REGION }} --project ${{ env.PROJECT_ID }}

      - name: Wait for External IPs and Log URLs
        run: |
          for i in {1..30}; do
            USER_ACC_MGMT_URL=$(kubectl get svc useraccmgmtserv -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
            if [[ -n "$USER_ACC_MGMT_URL" ]]; then break; fi
            sleep 10
          done
          if [[ -z "$USER_ACC_MGMT_URL" ]]; then
            echo "Error: UserAccMgmtServ IP not assigned after waiting."
            exit 1
          fi

          for i in {1..30}; do
            STORAGE_MGMT_URL=$(kubectl get svc storagemgmtserv -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
            if [[ -n "$STORAGE_MGMT_URL" ]]; then break; fi
            sleep 10
          done
          if [[ -z "$STORAGE_MGMT_URL" ]]; then
            echo "Error: StorageMgmtServ IP not assigned after waiting."
            exit 1
          fi

          echo "Deployed Service URLs:"
          echo "UserAccMgmtServ: http://$USER_ACC_MGMT_URL"
          echo "StorageMgmtServ: http://$STORAGE_MGMT_URL"

          if [[ $GITHUB_EVENT_NAME == "pull_request" ]]; then
            COMMENT_BODY="### Deployed URLs\n- [UsageMntrServ]($USAGE_MNTR_URL)\n- [UserAccMgmtServ](http://$USER_ACC_MGMT_URL)\n- [StorageMgmtServ](http://$STORAGE_MGMT_URL)"
            echo "$COMMENT_BODY" | gh pr comment ${{ github.event.pull_request.number }} --body -
          fi